export class Employee{
    constructor(
    public employeeId: number,
    public namaLengkap: string,
    public namaPanggilan: string,
    public gender: string,
    public tanggalLahir: Date,
    public kotaKelahiran: string,
    public agama: string,
    public noKtp: string,
    public uploadKtp: string,
    public alamat: string,
    public tinggi: string,
    public beratBadan: string,
    public golonganDarah: string,
    public kacamata: string,
    public statusPernikahan: string,
    public jumlahAnak: string,
    public emailemp: string,
    public noHP: string,
    public jabatan: string,
    public divisi: string,
    public akunInstagram: string,
    public noNpwp:  string,
    public uploadNpwp: string,
    public uploadImageSolo: string,
    public nomorMember: string,
    public pendidikanTerakhir: string,
    public namaPendidikan: string,
    public tahunKelulusan: string,
    public namaAyah: string,
    public pekerjaanAyah: string,
    public namaIbu: string,
    public pekerjaanIbu: string,
    public anakKeberapa: string,
    public jumlahSaudara: string,
    public namaKontakDarurat: string,
    public hubunganKontakDarurat: string,
    public noHpKontakDarurat: string,
    public kantorCabang: string,
    public statusKerja: string,
    public noRekBca: string,
    public hireDate: Date,
    public resignDate: Date
    ){}

}

